{% set version = "0.6.1" %}

package:
  name: ecole
  version: {{ version }}

source:
  url: https://github.com/ds4dm/ecole/archive/v{{ version }}.tar.gz
  sha256: ea41be85bdf7ed759eb54c2b250b2c86f619db7830f9e0ae9f4c28034b2d0b78

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make
  host:
    - scip
    - fmt
    - xtensor
    - xsimd
    - python
    - pip
    - pybind11
    - numpy >=1.11
    - xtensor-python
  run:
    - python
    - numpy
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
  run_constrained:
    - pyscipopt >=3.0.1

test:
  imports:
    - ecole
    - ecole.core
    - ecole.environment
  source_files:
    - libecole/tests/data/
    - python/tests
  requires:
    - pytest
    - pyscipopt
  commands:
    - python -m pytest --no-slow python/tests

about:
  home: https://www.ecole.ai/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Extensible Combinatorial Optimization Learning Environments
  doc_url: https://doc.ecole.ai/

extra:
  recipe-maintainers:
    - AntoinePrv
    - gasse
