conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
build_platform:
  # NO scip builds
  # linux_aarch64: linux_64
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
